// Generated by gencpp from file pointpillars/pointpillars.msg
// DO NOT EDIT!


#ifndef POINTPILLARS_MESSAGE_POINTPILLARS_H
#define POINTPILLARS_MESSAGE_POINTPILLARS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pointpillars
{
template <class ContainerAllocator>
struct pointpillars_
{
  typedef pointpillars_<ContainerAllocator> Type;

  pointpillars_()
    : message()
    , count(0)  {
    }
  pointpillars_(const ContainerAllocator& _alloc)
    : message(_alloc)
    , count(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef uint32_t _count_type;
  _count_type count;





  typedef boost::shared_ptr< ::pointpillars::pointpillars_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pointpillars::pointpillars_<ContainerAllocator> const> ConstPtr;

}; // struct pointpillars_

typedef ::pointpillars::pointpillars_<std::allocator<void> > pointpillars;

typedef boost::shared_ptr< ::pointpillars::pointpillars > pointpillarsPtr;
typedef boost::shared_ptr< ::pointpillars::pointpillars const> pointpillarsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pointpillars::pointpillars_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pointpillars::pointpillars_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pointpillars

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'pointpillars': ['/home/these/catkin_ws/src/pointpillars/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pointpillars::pointpillars_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pointpillars::pointpillars_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pointpillars::pointpillars_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pointpillars::pointpillars_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pointpillars::pointpillars_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pointpillars::pointpillars_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pointpillars::pointpillars_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89498e8c3e7e4e4d3ec5e32aa108f04d";
  }

  static const char* value(const ::pointpillars::pointpillars_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89498e8c3e7e4e4dULL;
  static const uint64_t static_value2 = 0x3ec5e32aa108f04dULL;
};

template<class ContainerAllocator>
struct DataType< ::pointpillars::pointpillars_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pointpillars/pointpillars";
  }

  static const char* value(const ::pointpillars::pointpillars_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pointpillars::pointpillars_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string message\n"
"uint32 count\n"
"\n"
;
  }

  static const char* value(const ::pointpillars::pointpillars_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pointpillars::pointpillars_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
      stream.next(m.count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pointpillars_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pointpillars::pointpillars_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pointpillars::pointpillars_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POINTPILLARS_MESSAGE_POINTPILLARS_H
